site_name: 概率论与数理统计 Probability-theory-and-mathematical-statistics
theme:
  name: material
  palette:
    primary: teal
    accent: blue
    scheme: slate
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
